"""empty message

Revision ID: 88481a812233
Revises: 100de57ea99f
Create Date: 2017-08-11 09:27:29.800633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88481a812233'
down_revision = '100de57ea99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('status', sa.SmallInteger(), server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'status')
    # ### end Alembic commands ###
