"""empty message

Revision ID: f3c9997be1fd
Revises: 88481a812233
Create Date: 2017-09-05 10:07:20.434356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c9997be1fd'
down_revision = '88481a812233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('NOME', sa.String(length=64), nullable=True))
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('tag', 'NOME')
    # ### end Alembic commands ###
